#!/usr/bin/env python

import sys
import alsamixer

mixer = alsamixer.Mixer()
mixer.attach()
mixer.load()

action = sys.argv[1]

if action == "get":
	element = alsamixer.Element(mixer, "Master")
	print(element.get_volume())
elif action == "set":
	element = alsamixer.Element(mixer, "Master")
	element.set_volume(int(sys.argv[1]))
else:
	sys.stderr.write("Onbekend commando (Thierryyyy, hooooooo!)")
	exit(1)
